//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rfvgyhn.Gnomoria.Mods.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rfvgyhn.Gnomoria.Mods.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Remove # to uncomment colors
        ///# MaterialName	R, G, B, A
        ///# A list of all material names can be found in Materials.xnb (need to unpack first)
        ///
        ///#coal		64, 64, 64, 255
        ///#copper		214, 74, 0, 255
        ///#malachite	28, 140, 70, 255
        ///#tin		127, 127, 127, 255
        ///#bronze		166, 125, 61, 255
        ///#iron		76, 76, 76, 255
        ///#steel		70, 130, 180, 255
        ///#lead		118, 136, 143, 255
        ///#silver		192, 192, 192, 255
        ///#gold		255, 215, 0, 255
        ///#rose gold	183, 110, 121, 255
        ///#platinum	229, 228, 226, 255
        ///#emerald	25, 233, 25, 255
        ///#sapphire	25, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaterialColorOverride {
            get {
                return ResourceManager.GetString("MaterialColorOverride", resourceCulture);
            }
        }
    }
}
